using Microsoft.Maui.Controls;
using System;
using System.Collections.Generic;

namespace Truth_or_drink_3
{
    public partial class Mix : ContentPage
    {
        // Lijst met vragen
        private readonly List<string> _questions = new()
        {
            "[Random speler], durf je te bellen naar de laatste persoon in je contactenlijst?",
            "[Random speler], durf je een bericht te sturen naar je ex?",
            "[Random speler], durf je een selfie te maken en direct te posten zonder filter?",
            "[Random speler], durf je 10 minuten lang alleen in rijm te praten?",
            "[Random speler], durf je een gênant geheim te delen dat niemand weet?",
            "[Random speler], durf je de persoon naast je een compliment te geven?",
            "[Random speler], durf je een dansmove te doen die je nooit eerder hebt geprobeerd?",
            "[Random speler], durf je een hap te nemen van iets dat je normaal nooit eet?",
            "[Random speler], durf je de eerste foto op je telefoon te laten zien?",
            "[Random speler], durf je het nummer van een willekeurige onbekende te bellen?",
            "[Random speler], durf je een lelijke gezichtsexpressie te maken en vast te houden?",
            "[Random speler], durf je een TikTok-dansje na te doen, zelfs als je het niet kent?",
            "[Random speler], durf je een lied te zingen zonder de tekst te kennen?",
            "[Random speler], durf je je telefoon aan de persoon links van je te geven voor 1 minuut?",
            "[Random speler], durf je iemand een gênante vraag te stellen?",
            "[Random speler], durf je een geheim over jezelf te vertellen?",
            "[Random speler], durf je een gek geluid te maken dat niemand verwacht?",
            "[Random speler], durf je een compliment te geven aan iemand die je normaal negeert?",
            "[Random speler], durf je een denkbeeldig gesprek te voeren met een object in de kamer?",
            "[Random speler], durf je een minuut lang stil te staan in een gekke pose?",
            "[Random speler], durf je te dansen zonder muziek?",
            "[Random speler], durf je een verhaal te verzinnen over hoe je in een andere stad bent beland?",
            "[Random speler], durf je te bellen naar een fastfoodrestaurant en een raar verzoek te doen?",
            "[Random speler], durf je iets uit je tas of zakken te laten zien wat je nu bij je hebt?",
            "[Random speler], durf je een willekeurige foto van je galerij te laten zien?",
            "[Random speler], durf je een geheim prijs te geven over je kindertijd?",
            "[Random speler], durf je een leugen te bekennen die je ooit hebt verteld?",
            "[Random speler], durf je iemand een gênante bijnaam te geven?",
            "[Random speler], durf je een dansje te doen op een willekeurig lied dat iemand kiest?",
            "[Random speler], durf je een slechte grap te vertellen?",
            "[Random speler], durf je een schattig geluid na te doen van een dier?",
            "[Random speler], durf je een liedje na te zingen dat iemand in de kamer kiest?",
            "[Random speler], durf je de persoon naast je iets te laten schrijven op je hand?",
            "[Random speler], durf je je meest recente appgesprek te openen en voor te lezen?",
            "[Random speler], durf je een object in de kamer te verkopen alsof je een verkoper bent?",
            "[Random speler], durf je iets te eten dat iemand anders kiest?",
            "[Random speler], durf je je volgende drankje te drinken zonder je handen te gebruiken?",
            "[Random speler], durf je een mop te verzinnen en nu meteen te vertellen?",
            "[Random speler], durf je je meest gênante foto te laten zien aan iedereen?",
            "[Random speler], durf je iemand anders een nieuwe outfit te laten kiezen uit jouw kleding?",
            "[Random speler], durf je een imitatie te doen van een beroemd persoon?",
            "[Random speler], durf je een emoji-verhaal te maken in de groepschat?",
            "[Random speler], durf je een geheime crush te bekennen (of verzin een)?",
            "[Random speler], durf je te zingen terwijl je een rare dans doet?",
            "[Random speler], durf je een rare accessoire te dragen voor de rest van het spel?",
            "[Random speler], durf je een gek geluid te maken elke keer dat je naam wordt genoemd?",
            "[Random speler], durf je een onbekend nummer te bellen en te vragen naar hun favoriete kleur?",
            "[Random speler], durf je een TikTok-video te maken en te posten?",
            "[Random speler], durf je een selfie te maken met iemand anders zijn telefoon?",
            "[Random speler], durf je iemand te vertellen wat je eerste indruk van hen was?",
            "[Random speler], durf je een schattige bijnaam te verzinnen voor jezelf en deze te gebruiken?",
            "[Random speler], durf je een slechte eigenschap van jezelf toe te geven?",
            "[Random speler], durf je een improvisatiedans te doen op een gek geluid?",
            "[Random speler], durf je je meest gênante chatbericht te delen?",
            "[Random speler], durf je iets stoms te zeggen in een groepschat?",
            "[Random speler], durf je je telefoonwachtwoord te delen (alleen grapje natuurlijk!)?",
            "[Random speler], durf je iemand een vraag te stellen die je normaal nooit zou vragen?",
            "[Random speler], durf je je vreemdste eigenschap te beschrijven?",
            "[Random speler], durf je een kussengevecht te starten met iemand in de kamer?",
            "[Random speler], durf je een dans op hakken na te doen (zelfs als je ze niet hebt)?",
            "[Random speler], durf je te vertellen wie je favoriete persoon in de kamer is?",
            "[Random speler], durf je een gênant moment uit je verleden te herbeleven?",
            "[Random speler], durf je het gekste wat je vandaag hebt gedaan te beschrijven?",
            "[Random speler], durf je iemand een geheim te ontfutselen?",
            "[Random speler], durf je te springen en een gek geluid te maken zonder reden?",
            "[Random speler], durf je een scène uit een horrorfilm na te spelen?",
            "[Random speler], durf je een vreemde gewoonte te onthullen die niemand kent?",
            "[Random speler], durf je iemand te vragen naar een gênant moment?",
            "[Random speler], durf je een grap te vertellen die niemand begrijpt?",
            "[Random speler], durf je je laatst beluisterde Spotify-nummer te laten zien?",
            "[Random speler], durf je te zeggen wat je echt denkt over de persoon tegenover je?",
            "[Random speler], durf je een emoji te sturen naar je laatste contact zonder uitleg?",
            "[Random speler], durf je een rare smoes te verzinnen en te delen?",
            "[Random speler], durf je een geheim over je dag te vertellen?",
            "[Random speler], durf je een gek geluid te maken en te doen alsof het normaal is?",
            "[Random speler], durf je je telefoon achter te laten voor 10 minuten?",
            "[Random speler], durf je iemand te laten raden wat je laatst gegeten hebt?",
            "[Random speler], durf je een slechte review over iets te verzinnen?",
            "[Random speler], durf je te zeggen wat je zou doen als je miljonair was?",
            "[Random speler], durf je te vragen wat iedereen echt van je denkt?",
            "[Random speler], durf je een rare dans uit te voeren met een willekeurig object?",
            "[Random speler], durf je een 'beste dag ooit'-verhaal te verzinnen?",
            "[Random speler], durf je iets raars te zeggen tegen iemand die je niet kent?",
            "[Random speler], durf je te doen alsof je een superheld bent voor 1 minuut?",
            "[Random speler], durf je een foto te kiezen en in een groepschat te delen?",
            "[Random speler], doe een gek geluid na dat je als kind vaak maakte.",
            "[Random speler], probeer te lopen alsof je op de maan bent voor de komende 3 rondes.",
            "[Random speler], spreek de komende 2 rondes alsof je een robot bent.",
            "[Random speler], imiteer je favoriete dier totdat iemand raadt wat het is.",
            "[Random speler], zing een fragment van je favoriete liedje zonder de tekst te gebruiken.",
            "[Random speler], dans alsof je een beroemdheid bent op de rode loper.",
            "[Random speler], doe alsof je een nieuwslezer bent en lees een krantenkop voor in een dramatische toon.",
            "[Random speler], doe alsof je een vlogger bent en introduceer de groep alsof ze je fans zijn.",
            "[Random speler], geef iemand in de groep een (goede) bijnaam op basis van hun uiterlijk of gedrag.",
            "[Random speler], stel een onmogelijke rekensom aan iemand en doe alsof je echt het antwoord verwacht.",
            "[Random speler], doe een perfecte imitatie van iemand anders in deze kamer.",
            "[Random speler], voer een nep telefoongesprek alsof je boos bent op de persoon aan de andere kant.",
            "[Random speler], spreek alsof je een geheim moet vertellen, maar zeg alleen onzin.",
            "[Random speler], doe alsof je een professionele danser bent en geef ons een korte show.",
            "[Random speler], neem een gekke selfie met iedereen in de kamer.",
            "[Random speler], draag een voorwerp uit de kamer alsof het een kroontje is en je een koning(in) bent.",
            "[Random speler], drink een glas water alsof je in een woestijn hebt overleefd.",
            "[Random speler], dans alsof je in een muziekvideoclip speelt.",
            "[Random speler], probeer zo goed mogelijk een bekende persoon na te doen zonder de naam te noemen.",
            "[Random speler], verzin een dramatische liefdesscène met iemand anders in de groep.",
            "[Random speler], imiteer de geluiden van drie verschillende dieren zonder te zeggen welke ze zijn.",
            "[Random speler], doe alsof je een superheld bent en introduceer jezelf en je krachten.",
            "[Random speler], doe alsof je een geheim agent bent die instructies geeft voor een missie.",
            "[Random speler], maak een hoed van een alledaags voorwerp en draag het voor de komende 3 rondes.",
            "[Random speler], fluister alles wat je zegt voor de komende ronde.",
            "[Random speler], maak een rare dansbeweging en laat iemand anders hem nadoen.",
            "[Random speler], vertel een verhaal, maar elke zin moet beginnen met dezelfde letter.",
            "[Random speler], voer een gesprek met een plant in de kamer alsof het een goede vriend is.",
            "[Random speler], maak een geluidsopname waarin je iemand overtuigt om een absurd product te kopen.",
            "[Random speler], doe alsof je een goochelaar bent en laat een 'truc' zien.",
            "[Random speler], neem een vreemde pose aan en blijf staan tot de volgende speler aan de beurt is.",
            "[Random speler], loop alsof je op een catwalk bent voor de komende twee rondes.",
            "[Random speler], doe alsof je een beroemde chef-kok bent en beschrijf een gerecht op een rare manier.",
            "[Random speler], maak een dans met alleen je handen.",
            "[Random speler], vertel een mop, maar doe alsof het een levensles is.",
            "[Random speler], maak een geluid alsof je een monster bent.",
            "[Random speler], introduceer jezelf alsof je een historisch figuur bent.",
            "[Random speler], spreek alsof je een wetenschapper bent die een doorbraak heeft ontdekt.",
            "[Random speler], zing een kinderliedje alsof het een opera is.",
            "[Random speler], doe alsof je probeert een mug in de kamer te vangen.",
            "[Random speler], gebruik alleen gebarentaal om de volgende vraag te beantwoorden.",
            "[Random speler], vertel een sprookje in 30 seconden met je eigen draai eraan.",
            "[Random speler], imiteer een huisdier dat je ooit hebt gehad of graag zou willen hebben.",
            "[Random speler], draag een vreemd voorwerp alsof het een hoed is voor de volgende ronde.",
            "[Random speler], loop alsof je voeten aan elkaar geplakt zijn.",
            "[Random speler], maak geluiden alsof je in een horrorfilm zit.",
            "[Random speler], stel je voor dat je een nieuwe sport uitvindt en laat ons zien hoe het werkt.",
            "[Random speler], praat alsof je een alien bent die net op aarde is geland.",
            "[Random speler], doe alsof je een beroemd atleet bent en geef een overwinningstoespraak.",
            "[Random speler], bedenk een nieuwe manier om hallo te zeggen en laat het zien.",
            "[Random speler], draai in een cirkel terwijl je je volgende beurt speelt.",
            "[Random speler], geef een weerbericht met een totaal verzonnen situatie.",
            "[Random speler], voer een dramatische interpretatie op van het openen van een deur.",
            "[Random speler], ga naar de andere kant van de kamer alsof je een geheim moet afleveren.",
            "[Random speler], praat alsof je een piraat bent voor de volgende twee rondes.",
            "[Random speler], speel een gitaar zonder dat er een echte gitaar is.",
            "[Random speler], maak een reclame voor een belachelijk product en verkoop het aan de groep.",
            "[Random speler], doe alsof je een beroemd schilder bent en schets iets met je vinger in de lucht.",
            "[Random speler], gebruik een willekeurig voorwerp alsof het je mobiele telefoon is en voer een gesprek.",
            "[Random speler], dans zonder je voeten te gebruiken.",
            "[Random speler], doe alsof je de presentator bent van een kinderprogramma.",
            "[Random speler], maak een nieuwe handshake met iemand anders in de groep.",
            "[Random speler], stel jezelf voor alsof je in een datingshow zit.",
            "[Random speler], voer een dramatische scène op waarin je afscheid neemt van iemand.",
            "[Random speler], fluister de tekst van een bekend lied alsof het een groot geheim is.",
            "[Random speler], creëer een kort toneelstuk van 10 seconden met een willekeurig voorwerp.",
            "[Random speler], doe alsof je net een prijs hebt gewonnen en bedank iedereen.",
            "[Random speler], loop alsof je door een modderig veld loopt.",
            "[Random speler], doe alsof je net hebt ontdekt dat je superkrachten hebt.",
            "[Random speler], imiteer een bekende tekenfilmfiguur.",
            "[Random speler], doe alsof je een ninja bent en laat je moves zien.",
            "[Random speler], vertel een verhaal met alleen geluidseffecten.",
            "[Random speler], maak een vliegtuig van papier en laat zien hoe ver het vliegt.",
            "[Random speler], dans alsof je op ijs staat.",
            "[Random speler], doe alsof je een spion bent die betrapt is.",
            "[Random speler], spreek alsof je een strenge leraar bent.",
            "[Random speler], speel een telefoongesprek na waarin je ruzie maakt met je provider.",
            "[Random speler], maak een gezicht alsof je een citroen eet.",
            "[Random speler], fluister alles wat je zegt totdat je weer aan de beurt bent.",
            "[Random speler], vertel een sprookje, maar vervang alle namen door fruitsoorten.",
            "[Random speler], doe alsof je een standbeeld bent voor de volgende ronde.",
            "[Random speler], imiteer een vogel en probeer te vliegen.",
            "[Random speler], geef iemand in de groep een hilarische bijnaam.",
            "[Random speler], introduceer een denkbeeldig huisdier aan de groep.",
            "[Random speler], vertel een mop terwijl je moet lachen.",
            "[Random speler], speel een scène na uit je favoriete film.",
            "[Random speler], verzin een absurde theorie over waarom de lucht blauw is.",
            "[Random speler], spreek alsof je een goeroe bent die wijsheid deelt.",
            "[Random speler], ga door de kamer alsof je je schoen kwijt bent.",
            "[Random speler], doe alsof je een spelshow host en stel een vraag.",
            "[Random speler], imiteer de persoon rechts van je.",
            "[Random speler], doe een armworstelwedstrijd met iemand anders in de groep.",
            "[Random speler], blaas een ballon op (of doe alsof) totdat hij knapt.",
            "[Random speler], doe alsof je een ouder bent die iemand straft.",
            "[Random speler], kruip door de kamer alsof je een baby bent.",
            "[Random speler], doe alsof je een danswedstrijd wint.",
            "[Random speler], doe alsof je een beroemd schilder bent en schilder in de lucht.",
            "[Random speler], loop alsof je op hoge hakken staat.",
            "[Random speler], geef een liefdesverklaring aan een willekeurig object in de kamer.",
            "[Random speler], doe alsof je een karaoke-wedstrijd wint.",
            "[Random speler], vertel een spannend verhaal over hoe je vandaag bent aangekomen.",
            "[Random speler], doe alsof je een vechtscène uit een film nadoet.",
            "[Random speler], leg uit hoe een onbekend voorwerp werkt alsof je een expert bent.",
            "[Random speler], zing een bekend lied, maar met verkeerde woorden.",
            "[Random speler], loop alsof je een model bent op een catwalk.",
            "[Random speler], vertel een geheim, maar het mag alleen klinken alsof het belangrijk is.",
            "[Random speler], speel een drumsolo op een denkbeeldige drumset.",
            "[Random speler], lach alsof je net een geweldige grap hebt gehoord.",
            "[Random speler], imiteer een sportcommentator terwijl je een willekeurige actie beschrijft.",
            "[Random speler], maak een dans waarbij je alleen je hoofd mag bewegen.",
            "[Random speler], stel je voor dat je de president bent en geef een speech.",
            "[Random speler], zing alsof je een musicalster bent.",
            "[Random speler], doe alsof je een hond bent die op zoek is naar iets.",
            "[Random speler], beweeg door de kamer alsof je een spook bent.",
            "[Random speler], vertel een mop zonder te glimlachen.",
            "[Random speler], speel een scène na waarin je een geheime boodschap moet doorgeven.",
            "[Random speler], doe alsof je een beroemd chef-kok bent die een gerecht serveert.",
            "[Random speler], vertel een grappig verhaal dat niet waar is.",
            "[Random speler], imiteer een robot die kapot gaat.",
            "[Random speler], praat alsof je een verkoper bent die iets absurds verkoopt.",
            "[Random speler], doe alsof je vastzit in slow motion.",
            "[Random speler], voer een denkbeeldige choreografie uit alsof je in een muziekvideo zit.",
            "[Random speler], doe alsof je een beroemde zanger bent tijdens een interview.",
            "[Random speler], loop door de kamer alsof je een geheim probeert te bewaren.",
            "[Random speler], maak een geluid alsof je een auto bent.",
            "[Random speler], praat alsof je een piraat bent voor de rest van de ronde.",
            "[Random speler], schrijf je naam in de lucht met je neus.",
            "[Random speler], introduceer de groep alsof je een stand-upcomedian bent.",
            "[Random speler], doe alsof je een acteur bent die auditie doet voor een drama.",
            "[Random speler], probeer een denkbeeldige vlieg te vangen.",
            "[Random speler], imiteer het geluid van regen.",
            "[Random speler], doe alsof je je favoriete sport beoefent.",
            "[Random speler], vertel een verhaal waarbij elk woord met dezelfde letter begint.",
            "[Random speler], voer een nep-toverspreuk uit alsof je een tovenaar bent.",
            "[Random speler], spreek alsof je een cartoonfiguur bent.",
            "[Random speler], maak een dramatisch gebaar alsof je net een belangrijke ontdekking hebt gedaan.",
            "[Random speler], probeer een grap te vertellen in een andere taal (of doe alsof).",
            "[Random speler], beweeg alsof je in een onzichtbare doos zit.",
            "[Random speler], doe alsof je een boze klant bent die klaagt bij de klantenservice.",
            "[Random speler], wat is het laatste dat je hebt gegoogled?",
            "[Random speler], wat is je grootste geheim?",
            "[Random speler], wie vind je het knapst in deze kamer?",
            "[Random speler], wat is je meest beschamende moment?",
            "[Random speler], wat is iets waar je trots op bent?",
            "[Random speler], wat is de gekste droom die je hebt gehad?",
            "[Random speler], wat is de engste droom die je ooit hebt gehad",
            "[Random speler], als het niet illegaal was, wie zou je vermoorden",
            "[Random speler], waar heb je de meeste spijt van",
            "[Random speler], wat is het meest kinderachtige dat je nogsteeds doet",
            "[Random speler], doe de WAP dans",
            "[Random speler], als je voor één dag een ander geslacht was, wat zou je doen?",
            "[Random speler], open een zakje chips/snoepjes zonder je handen te gebruiken",
            "[Random speler], wat is iets dat je met je vrienden doet, dat je niet met je partner zou willen doen?",
            "[Random speler], wie zou je bellen als je in de gevangenis zit?",
            "[Random speler], wat is het vreemdste dat je ooit hebt gedaan om iemand te imponeren",
            "[Random speler], als je één geheim van iemand in deze groep moest delen, welk geheim zou dat dan zijn",
            "[Random speler], wie van ons zou je het minst vertrouwen om je levensgeheimen aan te vertellen",
            "[Random speler], wat is de meest gênante situatie waarin je ooit in de buurt van iemand hier was",
            "[Random speler], als je iemand uit deze groep moest kussen voor een miljoen euro, wie zou je kiezen",
            "[Random speler], wat is het ergste dat je ooit tegen je ouders hebt gelogen",
            "[Random speler], wie in deze kamer zou het snelst een geheim verklappen",
            "[Random speler], wat is het grootste misverstand dat je ooit hebt gehad met iemand hier",
            "[Random speler], heb je ooit iemand in deze groep stiekem afgeschreven, en waarom",
            "[Random speler], wat is het meest ongemakkelijke dat je ooit hebt gehoord tijdens een gesprek met iemand uit deze groep",
            "[Random speler], wie zou je kiezen om mee naar een onbewoond eiland te gaan",
            "[Random speler], wat is de vreemdste gewoonte die je hebt, die niemand hier weet",
            "[Random speler], als je ons moest beschrijven met één woord, wat zou dat dan zijn",
            "[Random speler], wie zou je niet in vertrouwen nemen met je telefoon als je moest gaan slapen",
            "[Random speler], wat is het grootste risico dat je ooit hebt genomen dat goed uitpakte",
            "[Random speler], wat is het gekste dat je ooit hebt gedaan op een feestje zonder dat iemand het wist",
            "[Random speler], wie zou je niet vertrouwen met je Netflix-account",
            "[Random speler], wat is het ergste dat je ooit tegen iemand hebt gezegd in een ruzie",
            "[Random speler], wat is het meest gênante dat je ooit op social media hebt gepost?",
            "[Random speler], als je een superkracht zou kunnen kiezen, welke zou dat zijn en waarom?",
            "[Random speler], wie van deze groep zou je het eerst verlaten in een zombie-apocalypse?",
            "[Random speler], wat is het meest romantische gebaar dat je ooit hebt gedaan?",
            "[Random speler], wat is het raarste dat je ooit in de koelkast hebt gevonden?",
            "[Random speler], als je een beroemdheid zou kunnen daten, wie zou dat zijn?",
            "[Random speler], wat is het meest nutteloze dat je ooit hebt gekocht?",
            "[Random speler], wie in deze kamer zou het slechtst een geheim kunnen bewaren?",
            "[Random speler], wat is je grootste guilty pleasure op Netflix?",
            "[Random speler], wat is het meest gênante dat ooit in je browsergeschiedenis heeft gestaan?",
            "[Random speler], wie zou je kiezen om je wingman/wingwoman te zijn tijdens een avondje uit?",
            "[Random speler], wat is je meest rare gewoonte waar je je soms voor schaamt?",
            "[Random speler], als je een crimineel moest worden, wat zou je misdaad zijn?",
            "[Random speler], wat is het vreemdste compliment dat je ooit hebt gekregen?",
            "[Random speler], wie in deze kamer zou het snelst zijn baan opzeggen voor een miljoen euro?",
            "[Random speler], wat is de grootste leugen die je ooit hebt verteld aan een vriend(in)?",
            "[Random speler], wat is het meest gênante dat je ooit in een openbare ruimte hebt gedaan?",
            "[Random speler], als je een realityshow mocht starten, wie van ons zou je erin casten?",
            "[Random speler], wat is het vreemdste eten dat je ooit hebt geprobeerd?",
            "[Random speler], als je één ding kon veranderen aan jezelf, wat zou dat zijn?",
            "[Random speler], wie in deze groep zou je kiezen om een geheime missie mee uit te voeren?",
            "[Random speler], wat is het stomste advies dat je ooit hebt gegeven, maar dat werkte?",
            "[Random speler], als je een tattoo zou moeten nemen, wat zou het dan zijn en waarom?",
            "[Random speler], wie in deze groep zou je het minst snel laten babysitten voor je (toekomstige) kinderen?",
            "[Random speler], wat is het raarste dat iemand ooit tegen je heeft gezegd?",
            "[Random speler], als je één lied moest zingen op karaoke, welk lied zou je kiezen?",
            "[Random speler], wie in deze kamer zou het meest waarschijnlijk te laat komen op zijn/haar eigen bruiloft?",
            "[Random speler], wat is het meest gênante dat je ooit in je zak hebt gevonden?",
            "[Random speler], wie in deze groep zou het waarschijnlijkst verdwalen tijdens een reis?",
            "[Random speler], wat is het meest impulsieve dat je ooit hebt gedaan?",
            "[Random speler], als je morgen wakker zou worden in het lichaam van iemand hier, wie zou je kiezen?",
            "[Random speler], wat is het meest onverwachte dat iemand ooit over jou heeft onthuld?",
            "[Random speler], wie van ons zou volgens jou het beste een geheim agent kunnen zijn?",
            "[Random speler], wat is het slechtste cadeau dat je ooit hebt gegeven?",
            "[Random speler], als je een film over je leven zou maken, wie in deze groep zou je casten als de slechterik?",
            "[Random speler], als je één slechte gewoonte moest opgeven, welke zou dat zijn?",
            "[Random speler], wat is het meest gênante dat je ooit in een groepschat hebt gestuurd?",
            "[Random speler], wie van deze groep zou je bellen als je autopech had?",
            "[Random speler], wat is het ergste dat je ooit hebt gedaan om onder een verplichting uit te komen?",
            "[Random speler], wat is het meest illegale dat je ooit hebt gedaan?",
            "[Random speler], als je een wereldrecord kon breken, welke zou dat zijn?",
            "[Random speler], wie van deze groep zou je nooit met je huisdier vertrouwen?",
            "[Random speler], wat is het vreemdste wat je ooit in iemands badkamer hebt gevonden?",
            "[Random speler], wat is je meest gênante kindertijdverhaal?",
            "[Random speler], als je voor één dag een dier kon zijn, welk dier zou je kiezen?",
            "[Random speler], wat is het vreemdste bijgeloof waar je ooit in hebt geloofd?",
            "[Random speler], wie van ons zou het beste een geheim dubbel leven kunnen leiden?",
            "[Random speler], wat is het slechtste advies dat je ooit hebt gekregen?",
            "[Random speler], wie zou je het minst vertrouwen om je mee te helpen verhuizen?",
            "[Random speler], wat is de gekste plek waar je ooit in slaap bent gevallen?",
            "[Random speler], wat is het meest onverwachte cadeau dat je ooit hebt gekregen?",
            "[Random speler], als je één dag onzichtbaar kon zijn, wat zou je doen?",
            "[Random speler], wat is je grootste modeflater ooit?",
            "[Random speler], wie in deze groep zou je nooit om advies vragen over liefde?",
            "[Random speler], wat is het slechtste excuus dat je ooit hebt gebruikt?",
            "[Random speler], wie zou het meeste geld kunnen uitgeven tijdens een dagje shoppen?",
            "[Random speler], wat is het stomste wat je ooit hebt gedaan toen je boos was?",
            "[Random speler], wat is het grootste misverstand dat iemand ooit over jou heeft gehad?",
            "[Random speler], wie in deze groep zou het meest waarschijnlijk een wereldreis maken zonder iets te plannen?",
            "[Random speler], wat is de raarste bijnaam die je ooit hebt gehad?",
            "[Random speler], wat is het meest impulsieve dat je ooit online hebt gekocht?",
            "[Random speler], wie in deze groep zou het meest waarschijnlijk per ongeluk iets waardevols breken?",
            "[Random speler], wat is het stomste dat je ooit hebt gezegd tijdens een belangrijke afspraak?",
            "[Random speler], als je een fictieve wereld kon bezoeken, welke zou dat zijn?",
            "[Random speler], wie in deze groep zou je meest irritante huisgenoot zijn?",
            "[Random speler], wat is het raarste wat je ooit hebt gegeten en lekker vond?",
            "[Random speler], als je een superheldnaam moest kiezen, wat zou die zijn?",
            "[Random speler], wat is het meest gênante dat je ouders ooit tegen iemand hebben gezegd?",
            "[Random speler], wie in deze groep zou het beste een schurkenrol in een film kunnen spelen?",
            "[Random speler], wat is de vreemdste droom die je ooit hebt gehad en je nog steeds herinnert?",
            "[Random speler], wie in deze groep zou het slechtst zijn in een geheime missie?",
            "[Random speler], wat is je grootste blunder op het werk of op school?",
            "[Random speler], wat is het vreemdste geluid dat je ooit per ongeluk hebt gemaakt in het openbaar?",
            "[Random speler], als je één vraag kon stellen en zeker het antwoord zou krijgen, welke vraag zou dat zijn?",
            "[Random speler], wie van deze groep zou als eerste falen in een kookwedstrijd?",
            "[Random speler], wat is de grootste angst die je als kind had?",
            "[Random speler], wie in deze groep zou het langst zonder sociale media kunnen leven?",
            "[Random speler], wat is de meest gênante bijnaam die iemand ooit voor je heeft gebruikt?",
            "[Random speler], wie in deze groep zou je het eerst verliezen in een quiz?",
            "[Random speler], als je een lied moest kiezen dat je leven beschrijft, welk lied zou dat zijn?",
            "[Random speler], wat is het gekste verhaal dat je ooit hebt verzonnen om ergens onderuit te komen?",
            "[Random speler], wie in deze groep zou het meest waarschijnlijk een geheime aanbidder hebben?",
            "[Random speler], wat is het stomste dat je ooit hebt gedaan toen je dacht dat niemand keek?",
            "[Random speler], wie in deze groep zou de grappigste ouder zijn?",
            "[Random speler], wat is het meest gênante dat je ooit hebt gezegd tegen iemand die je leuk vond?"
        };

        // Lijst met spelers
        private readonly List<string> _players = new()
        {
            "Noud", "Eva", "Ricardo", "Dewi", "Rimke", "Damon", "Youp"
        };

        // Willekeurige generator
        private readonly Random _random = new();

        public Mix()
        {
            InitializeComponent();
        }

        // Methode die wordt uitgevoerd bij een tik op het scherm
        private void OnPageTapped(object sender, EventArgs e)
        {
            // Kies een willekeurige vraag
            string randomQuestion = _questions[_random.Next(_questions.Count)];

            // Kies een willekeurige speler
            string randomPlayer = _players[_random.Next(_players.Count)];

            // Vervang [Random speler] met de geselecteerde speler
            string displayedQuestion = randomQuestion.Replace("[Random speler]", randomPlayer);

            // Update de tekst van de vraag
            QuestionLabel.Text = displayedQuestion;
        }
    }
}
